name: GenZ Meet Deploy CI

on:
  # Triggers the workflow on push or pull request events but for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI_Pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use cached node_modules
        uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: |
          yarn install

      - name: Build
        run: |
          yarn build
          cp CNAME dist/

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: false
